- hosts: jumpbox
  tasks:
    - name: Backup file on local 
      copy:
        src: /empf/empfpd/git/life-admin-portal-app/build
        dest: /empf/empfpd/git/life-admin-portal-app/build_{{ ansible_date_time.iso8601 }}
        remote_src: yes
    - name: Copy the file from Jenkins to Jumpbox
      copy:
        src: /empf/var/lib/jenkins/workspace/life-ad-portal-ui/build
        dest: /empf/empfpd/git/life-admin-portal-app
