- hosts: jumpbox
  tasks:
    - name: Copy the file from Jenkins 
      synchronize:
        src=/empf/var/lib/jenkins/workspace/life-ad-portal-ui/build
        dest=/empf/empfpd/git/life-admin-portal-app/root
      delegate_to: 172.31.45.217
