- hosts: Jumpbox
  tasks:
    - name: Copy the file from Jenkins 
      synchronize:
        src=/empf/var/lib/jenkins/workspace/life-ad-portal-ui/build
        dest=/empf/empfpd/git/life-admin-portal-app/root
      delegate_to: ip-172-31-20-124.ap-east-1.compute.internal