import { config } from "../config";
const {
  SCHEME_BASE_URL,
  EMPF_EMPLOYEE_API_URL,
  EMPF_EMPLOYEE_CUSTOM_API_URL,
} = config;

// Server Address
export const SERVER_ADDRESS = EMPF_EMPLOYEE_CUSTOM_API_URL;
export const EMPLOYEE_API_URL = EMPF_EMPLOYEE_API_URL;
export const SCHEME_SERVER_ADDRESS = SCHEME_BASE_URL;

export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_FAIL = "FETCH_EMPLOYEES_FAIL";
export const VIEW_EMPLOYEE_SUCCESS = "VIEW_EMPLOYEE_SUCCESS";
export const VIEW_EMPLOYEE_FAIL = "VIEW_EMPLOYEE_FAIL";
export const SEARCH_MEMBERS_SUCCESS = "SEARCH_MEMBERS_SUCCESS";
export const SEARCH_MEMBERS_FAIL = "SEARCH_MEMBERS_FAIL";
export const CREATE_QUERY_SUCCESS = "CREATE_QUERY_SUCCESS";
export const FETCH_GENDER_SUCCESS = "FETCH_GENDER_SUCCESS";
export const FETCH_GENDER_FAIL = "FETCH_GENDER_FAIL";
export const FETCH_ID_SUCCESS = "FETCH_ID_SUCCESS";
export const FETCH_ID_FAIL = "FETCH_ID_FAIL";
export const FETCH_NATIONALITY_SUCCESS = "FETCH_NATIONALITY_SUCCESS";
export const FETCH_NATIONALITY_FAIL = "FETCH_NATIONALITY_FAIL";
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEE_FAIL = "FETCH_EMPLOYEE_FAIL";
export const FETCH_INDUSTRY_TYPE_SUCCESS = "FETCH_INDUSTRY_TYPE_SUCCESS";
export const FETCH_INDUSTRY_TYPE_FAIL = "FETCH_INDUSTRY_TYPE_FAIL";
export const FETCH_SCHEME_TYPE_SUCCESS = "FETCH_SCHEME_TYPE_SUCCESS";
export const FETCH_SCHEME_TYPE_FAIL = "FETCH_SCHEME_TYPE_FAIL";
export const FETCH_OCCUPATION_SUCCESS = "FETCH_OCCUPATION_SUCCESS";
export const FETCH_OCCUPATION_FAIL = "FETCH_OCCUPATION_FAIL";
export const FETCH_STATUS_SUCCESS = "FETCH_STATUS_SUCCESS";
export const FETCH_STATUS_FAIL = "FETCH_STATUS_FAIL";
export const FETCH_POB_SUCCESS = "FETCH_POB_SUCCESS";
export const FETCH_POB_FAIL = "FETCH_POB_FAIL";

// user side
export const GET_USER = "GET_USER";

/// added
export const GET_USER_DETAILS = "GET_USER_DETAILS";
