import { config } from '../config';
const { REG_BASE_API_URL } = config;

// Server Address
export const SERVER_ADDRESS = REG_BASE_API_URL;

export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const VIEW_EMPLOYEE_SUCCESS = 'VIEW_EMPLOYEE_SUCCESS';
export const SEARCH_MEMBERS = 'SEARCH_MEMBERS';
export const CREATE_QUERY_SUCCESS = 'CREATE_QUERY_SUCCESS';
export const FETCH_GENDER_SUCCESS = 'FETCH_GENDER_SUCCESS';
export const FETCH_GENDER_FAIL = 'FETCH_GENDER_FAIL';
export const FETCH_ID_SUCCESS = 'FETCH_ID_SUCCESS';
export const FETCH_ID_FAIL = 'FETCH_ID_FAIL';
export const FETCH_NATIONALITY_SUCCESS = 'FETCH_NATIONALITY_SUCCESS';
export const FETCH_NATIONALITY_FAIL = 'FETCH_NATIONALITY_FAIL';
