export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const VIEW_EMPLOYEE_SUCCESS = 'VIEW_EMPLOYEE_SUCCESS';
export const SEARCH_MEMBERS = 'SEARCH_MEMBERS';
export const CREATE_QUERY_SUCCESS = 'CREATE_QUERY_SUCCESS';
