export const labels = {
  // TOP MENU BAR
  textAsLogo: "eMPF",
  pageHeader: "Admin Portal",
  jobPosition: "Admin Operator",

  // SIDE BAR MENU
  dashboard: "Dashboard",
  company: "Company",
  individual: "Individual",
  employer: "Employer",
  employee: "Employee",

  // PAGE TITLE HEADER
  eMPF_ID: "eMPF ID ",
  memberNo: "Member No. ",
  employerNO: "Employer NO.",

  // EMPLOYEE DETAIL
  employmentDetail: "Employment Detail",
  schemeName: "Name of Scheme",
  employerName: "Name of Employer",
  er_id: "ER ID",
  branch: "Branch",
  branchId: "Branch ID",
  status: "Status",
  effectiveDate: "Effective Date", // same reference in employee detail termination
  memberDetail: "Member Detail",
  memberName: "Member Name",
  acctType: "Account Type",
  eMPF_No: "eMPF No.",
  acctId: "Account ID",
  staffNo: "Staff No.",
  dateJoin: "Date Join Scheme",
  terminationDate: "Termination Date",
  /// added
  schemeTitle:
    "MPF Scheme LSP / SP Offect Sequence (for Multiple Account Case)",
  terminationTitle: "Termination Detail",
  last_date: "Last Date of Employment",
  termination_reason: "Termination Reason",
  entitle_to: "Entitle to LSP / SP ?",
  lsp_details: "LSP / SP Details",
  entitle_lsp: "Entitle to LSP / SP ?",
  total_entitle_amount: "Total LSP/SP Entitlement Amount",
  pay_amount_er: "Payment Amount by ER",

  // MEMBER ENQUIRY
  member_enquiry: "Member Enquiry",
  title: "Title",
  personal_info: "Personal Information",
  mpf_id: "MPF ID",
  english_name: "Member Name",
  chinese_name: "Member Name (Chinese)",
  gender: "Gender",
  id_type: "ID Type",
  id_number: "ID Number",
  date_of_birth: "Date of Birth",
  nationality: "Nationality",
  place_of_birth: "Place of Birth",
  mobile_number: "Mobile Number",
  address: "Address",
  email: "Email",
  emp_info: "Employment Information",
  date_of_employment: "Date of Employment",
  employee_type: "Employee Type",
  reported_industry_type: "Reported Industry Type",
  occupation: "Occupation",
  mpf_scheme_name: "MPF Scheme Name",
  tax_residency: "Tax Residency",
  tin: "TIN",
  status: "Status",
  member_reg_view: "Member Registration View",
  first_name: "First Name",
  last_name: "Last Name",
  first_name: "First Name (Chinese)",
  last_name: "Last Name (Chinese)",
  secondary_mobile_no: "Secondary Mobile Number",
  residential_address: "Residential Address",
  correspondence_address: "Correspondence Address",
  preferred_communication_channel: "Preferred Communication Channel",
  other_info: "Other Information",
  preferred_communication_language: "Preferred Communication Language",
  recv_paper_form_notif_docs: "Receive Paper Form Notifications and Document",
};
