export const labels = {
  memberEnquiry: 'Member Enquiry',
  title: 'Title',
  personal_info: 'Personal Information',
  mpf_id: 'MPF ID',
  english_name: 'Member Name',
  chinese_name: 'Member Name (Chinese)',
  gender: 'Gender',
  id_type: 'ID Type',
  id_number: 'ID Number',
  date_of_birth: 'Date of Birth',
  nationality: 'Nationality',
  place_of_birth: 'Place of Birth',
  mobile_number: 'Mobile Number',
  address: 'Address',
  email: 'Email',
  emp_info: 'Employment Information',
  date_of_employment: 'Date of Employment',
  employee_type: 'Employee Type',
  reported_industry_type: 'Reported Industry Type',
  occupation: 'Occupation',
  mpf_scheme_name: 'MPF Scheme Name',
  tax_residency: 'Tax Residency',
  tin: 'TIN',
  status: 'Status',
  member_reg_view: 'Member Registration View',
  first_name: 'First Name',
  last_name: 'Last Name',
  first_name_chinese: 'First Name (Chinese)',
  last_name_chinese: 'Last Name (Chinese)',
  secondary_mobile_no: 'Secondary Mobile Number',
  residential_address: 'Residential Address',
  correspondence_address: 'Correspondence Address',
  preferred_communication_channel: 'Preferred Communication Channel',
  other_info: 'Other Information',
  preferred_communication_language: 'Preferred Communication Language',
  recv_paper_form_notif_docs: 'Receive Paper Form Notifications and Document',
  searchResult: 'Search Result',
  editSearch: 'Edit Search',
  newSearch: 'New Search',
  backToSearch: 'BACK TO SEARCH',
  // company profile
  companyRegistrationInfo: "Company Registration Information",
  companyNameEng: "Company Name (English)",
  companyNameChi: "Company Name (Chinese)",
  typeOfCompany: "Type of Company",
  dateOfIncorporation: "Date of Incorporation",
  placeOfIncorporation: "Place of Incorporation",
  registrationType: "Registration Type",
  registrationNumber: "Registration Number",
  branchName: "Branch Number",
  natureOfBusiness: "Nature of Business",
  preferredLanguage: "Prefered Communication Language",
  registeredOfficeAddress: "Registered Office Address",
  businessAddress: "Business Address",
  correspondenceAddress: "Correspondence Address",
  authorizedPerson: "Authorized Person(s) of Employer",
  lastNameEng: "Last Name in English",
  lastNameChi: "Last Name in Chinese",
  firstNameEng: "first Name in English",
  firstNameChi: "first Name in Chinese",
  primaryContactPerson: "Primary Contact Person",
  nameTitle: "Title",
  jobTitle: "Job Title",
  telephoneNumber: "Telephone No.",
  mobilePhoneNumber: "Mobile Phone No.",
  emailAddress: "Email Address",
  secondaryContactPerson: "Secondary Contact Person",
  supportingDocs: "Supporting for Business Registration / Partnership Deed / Evidence of Unincorporated",
  fileName: "File Name",
  view: "View",
}
